name: APK/AAB

env:
  module: app
  buildpath: build/outputs
  basename: refuel-tracker

on:
  workflow_run:
    workflows: [ "Android CI" ]
    branches: [ "master" ]
    types:
      - completed
  workflow_dispatch:

jobs:
  upload-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Set current day in env
        run: echo "today=$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Fail when CI build was not successful
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        run: exit 1
      - uses: actions/checkout@v4
      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: gradlew exec
        run: chmod +x gradlew
      - name: Build release apk
        run: ./gradlew ${{ env.module }}:assembleRelease
      - name: Build release aab
        run: ./gradlew ${{ env.module }}:bundleRelease
      # remove or keep artifact upload?
      #- name: Upload apk
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: ${{ env.basename }}-${{ env.today }}-apk
      #    path: ${{ env.module }}/${{ env.buildpath }}/apk/release/
      #- name: Upload aab
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: ${{ env.basename }}-${{ env.today }}-aab
      #    path: ${{ env.module }}/${{ env.buildpath }}/bundle/release/
      - name: Rename apk
        run: mv ${{ env.module }}/${{ env.buildpath }}/apk/release/*.apk ${{ env.module }}/${{ env.buildpath }}/apk/release/${{ env.basename }}-${{ env.today }}.apk
      - name: Release dev build # TODO: look into used workflow and see if we can eliminate the warning
        uses: marvinpinto/action-automatic-releases@v1.2.1
        # if: github.ref_type == 'branch' # not needed anymore, this is triggered from a previous workflow run now
        with:
          repo_token: "${{ secrets.RELEASE }}"
          automatic_release_tag: "dev"
          prerelease: true
          title: "Development Build"
          files: |
            ${{ env.module }}/${{ env.buildpath }}/apk/release/*.apk