name: Version release to Github

env:
  module: app
  buildpath: build/outputs
  basename: refuel-tracker

on:
  push:
    tags:
      - "*.*.*"

jobs:
  make-release:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4
      - name: setup jdk 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: gradlew exec
        run: chmod +x gradlew
      - name: Build release apk
        run: ./gradlew ${{ env.module }}:assembleRelease
      - name: Rename apk
        run: mv ${{ env.module }}/${{ env.buildpath }}/apk/release/*.apk ${{ env.module }}/${{ env.buildpath }}/apk/release/${{ env.basename }}-${{ github.ref_name }}.apk
      - name: Github Release
        uses: softprops/action-gh-release@v2.2.1
        if: github.ref_type == 'tag'
        with:
          files: |
            ${{ env.module }}/${{ env.buildpath }}/apk/release/*.apk
          token: ${{ secrets.RELEASE }}